# Site settings
title: "Chance Johnson"
description: "My resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Chance Johnson"
resume_title:                   "Penetration Tester"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "chancej715@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "872-228-7732"
resume_contact_address:         "Chicago, IL"

resume_header_contact_info:     "Chicago, IL • 872-228-7732 • chancej715@gmail.com"
display_header_contact_info:    "false"

resume_header_intro:            "<p>I am a self-employed full stack developer with a background in software development in JavaScript, Python, and C. I am pursuing studies towards the Offensive Security Certified Professional (OSCP) examination, and I am actively seeking an opportunity to enter the cyber security field, particularly as a penetration tester.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/chancej715"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/chancej715/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://chancej715.github.io/resume/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
